export const checkboxStyle = {
  general: {
    border: "1px solid gray",
    cursor: "pointer",
    fontWeight: "900",
    paddingBottom: ".35rem",
    paddingLeft: ".2rem",
    paddingRight: ".5rem",
    paddingTop: ".35rem",
    position: "relative",
    verticalAlign: "middle",
    marginLeft: ".25rem",
  },
  label: {
    position: "absolute",
    top: 0,
    left: 0,
    lineHeight: "1rem",
    paddingRight: ".5rem",
  },
  sm: {
    fontSize: ".9rem",
    height: ".3rem",
    lineHeight: ".3rem",
    maxHeight: ".3rem",
    maxWidth: ".3rem",

    width: ".3rem",
  },
  normal: {
    fontSize: "1.5rem",
    height: ".75rem",
    lineHeight: ".75rem",
    maxHeight: ".75rem",
    maxWidth: "1rem",
    width: ".75rem",
  },
  lg: {
    fontSize: "1.8rem",
    height: "1rem",
    lineHeight: "1rem",
    maxHeight: "1rem",
    maxWidth: "1rem",
    width: "1rem",
  },
  round: "50%",
  rounded: ".25rem",
};
